# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EtcdTui < Formula
  desc "Terminal user interface for etcd"
  homepage "https://github.com/aleksandersh/etcd-tui/"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/aleksandersh/etcd-tui/releases/download/v0.0.1/etcd-tui_ darwin_x86_64.tar.gz"
      sha256 "03e4c9a58963bd6fa6a3d039fef10459d55564e75a514dbf538d8636c0e0ccfd"

      def install
        bin.install "etcd-tui"
      end
    end
    on_arm do
      url "https://github.com/aleksandersh/etcd-tui/releases/download/v0.0.1/etcd-tui_ darwin_arm64.tar.gz"
      sha256 "0c05924654e8eeb7255a4559b4c564c58801789ea0c667ffa15c92d08b5e3e6c"

      def install
        bin.install "etcd-tui"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aleksandersh/etcd-tui/releases/download/v0.0.1/etcd-tui_ linux_x86_64.tar.gz"
        sha256 "a3c52911fb5fc280261197e795ec9a1549891b8cc9bebaa03854b4f6a7320318"

        def install
          bin.install "etcd-tui"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/aleksandersh/etcd-tui/releases/download/v0.0.1/etcd-tui_ linux_armv6.tar.gz"
        sha256 "e92cad9f78f3504909cbc70fd59783b2b199dc16aff0f6f4e032a3ff2387055d"

        def install
          bin.install "etcd-tui"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aleksandersh/etcd-tui/releases/download/v0.0.1/etcd-tui_ linux_arm64.tar.gz"
        sha256 "df6c7b99e6fc54f0f4c8605c9eca79728f8d74f79c89ea98649efd15b6ae3971"

        def install
          bin.install "etcd-tui"
        end
      end
    end
  end

  test do
    system "#{bin}/etcd-tui --version"
  end
end
