# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EtcdTui < Formula
  desc "Terminal user interface for etcd"
  homepage "https://github.com/aleksandersh/etcd-tui/"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/aleksandersh/etcd-tui/releases/download/v0.0.1/etcd-tui_darwin_amd64.tar.gz"
      sha256 "b049100e175a04a143e1b11818f33fbfa34d12280f620d8f9670fe5b4d3dceed"

      def install
        bin.install "etcd-tui"
      end
    end
    on_arm do
      url "https://github.com/aleksandersh/etcd-tui/releases/download/v0.0.1/etcd-tui_darwin_arm64.tar.gz"
      sha256 "bfe62d48b6d0fff6237f8deeaf8809e23d6b518166fb6304b1580862c173f22e"

      def install
        bin.install "etcd-tui"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aleksandersh/etcd-tui/releases/download/v0.0.1/etcd-tui_linux_amd64.tar.gz"
        sha256 "1c662f24df3bd2ac17b712003d49063db05cbc69f290f9278b14a6afbd701c26"

        def install
          bin.install "etcd-tui"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/aleksandersh/etcd-tui/releases/download/v0.0.1/etcd-tui_linux_arm.tar.gz"
        sha256 "85330309a26520039a5eea0bcb0924e17723820c09575558a2386ac5b66a23bd"

        def install
          bin.install "etcd-tui"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aleksandersh/etcd-tui/releases/download/v0.0.1/etcd-tui_linux_arm64.tar.gz"
        sha256 "d195ff18c10d044a294451b1b9b9cec976e62e19e2866696ddcb6630c3e4c0de"

        def install
          bin.install "etcd-tui"
        end
      end
    end
  end

  test do
    system "#{bin}/etcd-tui --version"
  end
end
